import SideBar from '../../components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chatgpt Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <div className="flex">
          {/* sidebar */}
          <SideBar />
          {/* nottification */}
          <div className="bg-[#343541] flex-1">{children}</div>
          
          </div>
        </body>
    </html>
  )
}
